<a href="https://colab.research.google.com/github/vnmrsharma/CANIS/blob/main/Canis_hackathon_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CANIS hackathon notebook

## Import libraries and modules

In [58]:
import pandas as pd

# !pip install -q tensorflow-model-optimization

import tempfile
import os
import time

import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

from tensorflow import keras

# import pillow
import matplotlib
import wordcloud

In [59]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [60]:
true_df = pd.read_csv("/content/drive/MyDrive/Canis_hackathon/DataSet_Misinfo_TRUE.csv")
fake_df = pd.read_csv("/content/drive/MyDrive/Canis_hackathon/DataSet_Misinfo_FAKE.csv")

display(true_df)
display(fake_df)

       Unnamed: 0                                               text
0               0  The head of a conservative Republican faction ...
1               1  Transgender people will be allowed for the fir...
2               2  The special counsel investigation of links bet...
3               3  Trump campaign adviser George Papadopoulos tol...
4               4  President Donald Trump called on the U.S. Post...
...           ...                                                ...
34970       34970  Most conservatives who oppose marriage equalit...
34971       34971  The freshman senator from Georgia quoted scrip...
34972       34972  The State Department told the Republican Natio...
34973       34973  ADDIS ABABA, Ethiopia —President Obama convene...
34974       34974  Jeb Bush Is Suddenly Attacking Trump. Here's W...

[34975 rows x 2 columns]

       Unnamed: 0                                               text
0               0  Donald Trump just couldn t wish all Americans ...
1               1  House Intelligence Committee Chairman Devin Nu...
2               2  On Friday, it was revealed that former Milwauk...
3               3  On Christmas day, Donald Trump announced that ...
4               4  Pope Francis used his annual Christmas Day mes...
...           ...                                                ...
43637       44422  The USA wants to divide Syria.\r\n\r\nGreat Br...
43638       44423  The Ukrainian coup d'etat cost the US nothing ...
43639       44424  The European Parliament falsifies history by d...
43640       44425  The European Parliament falsifies history by d...
43641       44426  A leading FSB officer, Segey Beseda, said duri...

[43642 rows x 2 columns]

## Data cleaning

In [61]:
true_df = true_df.drop('Unnamed: 0',axis=1)
true_df["label"] = 1

display(true_df)

                                                    text  label
0      The head of a conservative Republican faction ...      1
1      Transgender people will be allowed for the fir...      1
2      The special counsel investigation of links bet...      1
3      Trump campaign adviser George Papadopoulos tol...      1
4      President Donald Trump called on the U.S. Post...      1
...                                                  ...    ...
34970  Most conservatives who oppose marriage equalit...      1
34971  The freshman senator from Georgia quoted scrip...      1
34972  The State Department told the Republican Natio...      1
34973  ADDIS ABABA, Ethiopia —President Obama convene...      1
34974  Jeb Bush Is Suddenly Attacking Trump. Here's W...      1

[34975 rows x 2 columns]

In [62]:
fake_df = fake_df.drop('Unnamed: 0',axis=1)
fake_df["label"] = 0

display(fake_df)

                                                    text  label
0      Donald Trump just couldn t wish all Americans ...      0
1      House Intelligence Committee Chairman Devin Nu...      0
2      On Friday, it was revealed that former Milwauk...      0
3      On Christmas day, Donald Trump announced that ...      0
4      Pope Francis used his annual Christmas Day mes...      0
...                                                  ...    ...
43637  The USA wants to divide Syria.\r\n\r\nGreat Br...      0
43638  The Ukrainian coup d'etat cost the US nothing ...      0
43639  The European Parliament falsifies history by d...      0
43640  The European Parliament falsifies history by d...      0
43641  A leading FSB officer, Segey Beseda, said duri...      0

[43642 rows x 2 columns]

## Data segmentation/classification

## Data model implementation

## Data model evaluation

## Data model infographics compilation